"""initial migration

Revision ID: 3d64be8fda55
Revises: 
Create Date: 2026-03-29 19:59:52.933083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d64be8fda55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id_number', sa.String(length=50), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('academic_status', sa.Enum('active', 'probation', 'graduated', 'dropped', name='academicstatus'), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('academic_history', sa.String(length=1000), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('scholarship_status', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_id_number', 'students', ['student_id_number'], unique=False)
    op.create_index('idx_student_user', 'students', ['user_id'], unique=False)
    op.create_index(op.f('ix_students_student_id_number'), 'students', ['student_id_number'], unique=True)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('assignments',
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('allow_late_submission', sa.Boolean(), nullable=False),
    sa.Column('late_penalty_percent', sa.Float(), nullable=False),
    sa.Column('file_types_allowed', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_course', 'assignments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_table('attendances',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'excused', name='attendancestatus'), nullable=False),
    sa.Column('marked_by', sa.String(length=36), nullable=False),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendance_course', 'attendances', ['course_id'], unique=False)
    op.create_index('idx_attendance_date', 'attendances', ['date'], unique=False)
    op.create_index('idx_attendance_student', 'attendances', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendances_course_id'), 'attendances', ['course_id'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_marked_by'), 'attendances', ['marked_by'], unique=False)
    op.create_index(op.f('ix_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'completed', name='coursestatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollment_course', 'course_enrollments', ['course_id'], unique=False)
    op.create_index('idx_enrollment_student', 'course_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_student_id'), 'course_enrollments', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('component_type', sa.Enum('assignment', 'quiz', 'midterm', 'final', name='componenttype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grade_course', 'grades', ['course_id'], unique=False)
    op.create_index('idx_grade_student', 'grades', ['student_id'], unique=False)
    op.create_index(op.f('ix_grades_course_id'), 'grades', ['course_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', 'in_app', name='channel'), nullable=False),
    sa.Column('notification_type', sa.Enum('announcement', 'grade', 'attendance', 'deadline', 'general', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_course', 'notifications', ['course_id'], unique=False)
    op.create_index('idx_notification_recipient', 'notifications', ['recipient_id'], unique=False)
    op.create_index('idx_notification_sender', 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_course_id'), 'notifications', ['course_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_table('submissions',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('plagiarism_score', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'graded', 'rejected', name='submissionstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_assignment', 'submissions', ['assignment_id'], unique=False)
    op.create_index('idx_submission_student', 'submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_index('idx_submission_student', table_name='submissions')
    op.drop_index('idx_submission_assignment', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_course_id'), table_name='notifications')
    op.drop_index('idx_notification_sender', table_name='notifications')
    op.drop_index('idx_notification_recipient', table_name='notifications')
    op.drop_index('idx_notification_course', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_course_id'), table_name='grades')
    op.drop_index('idx_grade_student', table_name='grades')
    op.drop_index('idx_grade_course', table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_course_enrollments_student_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_index('idx_enrollment_student', table_name='course_enrollments')
    op.drop_index('idx_enrollment_course', table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_attendances_student_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_marked_by'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_course_id'), table_name='attendances')
    op.drop_index('idx_attendance_student', table_name='attendances')
    op.drop_index('idx_attendance_date', table_name='attendances')
    op.drop_index('idx_attendance_course', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_index('idx_assignment_course', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id_number'), table_name='students')
    op.drop_index('idx_student_user', table_name='students')
    op.drop_index('idx_student_id_number', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
